// Generated by gencpp from file test_service/test_service.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_MESSAGE_TEST_SERVICE_H
#define TEST_SERVICE_MESSAGE_TEST_SERVICE_H

#include <ros/service_traits.h>


#include <test_service/test_serviceRequest.h>
#include <test_service/test_serviceResponse.h>


namespace test_service
{

struct test_service
{

typedef test_serviceRequest Request;
typedef test_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test_service
} // namespace test_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_service::test_service > {
  static const char* value()
  {
    return "824d60fc841435159cb0442f45e7ceac";
  }

  static const char* value(const ::test_service::test_service&) { return value(); }
};

template<>
struct DataType< ::test_service::test_service > {
  static const char* value()
  {
    return "test_service/test_service";
  }

  static const char* value(const ::test_service::test_service&) { return value(); }
};


// service_traits::MD5Sum< ::test_service::test_serviceRequest> should match
// service_traits::MD5Sum< ::test_service::test_service >
template<>
struct MD5Sum< ::test_service::test_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_service::test_service >::value();
  }
  static const char* value(const ::test_service::test_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_service::test_serviceRequest> should match
// service_traits::DataType< ::test_service::test_service >
template<>
struct DataType< ::test_service::test_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::test_service::test_service >::value();
  }
  static const char* value(const ::test_service::test_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_service::test_serviceResponse> should match
// service_traits::MD5Sum< ::test_service::test_service >
template<>
struct MD5Sum< ::test_service::test_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_service::test_service >::value();
  }
  static const char* value(const ::test_service::test_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_service::test_serviceResponse> should match
// service_traits::DataType< ::test_service::test_service >
template<>
struct DataType< ::test_service::test_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::test_service::test_service >::value();
  }
  static const char* value(const ::test_service::test_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_SERVICE_MESSAGE_TEST_SERVICE_H
