// Generated by gencpp from file test_service/test_serviceRequest.msg
// DO NOT EDIT!


#ifndef TEST_SERVICE_MESSAGE_TEST_SERVICEREQUEST_H
#define TEST_SERVICE_MESSAGE_TEST_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_service
{
template <class ContainerAllocator>
struct test_serviceRequest_
{
  typedef test_serviceRequest_<ContainerAllocator> Type;

  test_serviceRequest_()
    : a(0)
    , b(0)
    , c(0)  {
    }
  test_serviceRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)
    , c(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;

   typedef int64_t _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::test_service::test_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_service::test_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct test_serviceRequest_

typedef ::test_service::test_serviceRequest_<std::allocator<void> > test_serviceRequest;

typedef boost::shared_ptr< ::test_service::test_serviceRequest > test_serviceRequestPtr;
typedef boost::shared_ptr< ::test_service::test_serviceRequest const> test_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_service::test_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_service::test_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_service::test_serviceRequest_<ContainerAllocator1> & lhs, const ::test_service::test_serviceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_service::test_serviceRequest_<ContainerAllocator1> & lhs, const ::test_service::test_serviceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_service::test_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_service::test_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_service::test_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_service::test_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service::test_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_service::test_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_service::test_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8559b52d432bccd240703f31aeca517";
  }

  static const char* value(const ::test_service::test_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8559b52d432bccdULL;
  static const uint64_t static_value2 = 0x240703f31aeca517ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_service::test_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_service/test_serviceRequest";
  }

  static const char* value(const ::test_service::test_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_service::test_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
"int64 c\n"
;
  }

  static const char* value(const ::test_service::test_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_service::test_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_service::test_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_service::test_serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<int64_t>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_SERVICE_MESSAGE_TEST_SERVICEREQUEST_H
